### ISSUE TITLE
Doesn't run without an X session.

### ISSUE THREAD

**Issue by AnAverageHuman** [AnAverageHuman/tomato-connoisseurs#1]
```
No protocol specified
Exception in thread "main" java.lang.InternalError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
        at java.awt.Window.initGC(Window.java:467)
        at java.awt.Window.init(Window.java:487)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:174)
        at core.Core.<init>(Core.java:48)
        at game.Woo.<init>(Woo.java:28)
        at game.Woo.main(Woo.java:201)

```

```
Loading....:

Robot did not initialize.
Must use turn-based input :(
java.awt.AWTException: headless environment
        at java.awt.Robot.<init>(Robot.java:94)
        at InputGrabber.<init>(InputGrabber.java:34)
        at InputClient.<init>(InputClient.java:47)
        at Woo.main(Woo.java:19)
Connecting to client...
connected!

-e
███████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
████████████
███████████

Exception in thread "Thread-1" java.lang.NullPointerException
        at InputGrabber.flushInput(InputGrabber.java:67)
        at InputClient.run(InputClient.java:87)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by AnAverageHuman** [comment]
Fixed with https://github.com/AnAverageHuman/tomato-connoisseurs/commit/8b22a1f9acbb190808573518452cb63468a149e4.
